use crate::MathNode;

/// 将 LaTeX 命令名映射为具体的 MathNode (Identifier 或 Operator)
/// 包含了 400 多个由 KaTeX 定义的常用希腊字母、箭头、数学符号等。
pub fn lookup_symbol(cmd: &str) -> Option<MathNode> {
    match cmd {
        "equiv" => Some(MathNode::Operator("≡".to_string())),
        "prec" => Some(MathNode::Operator("≺".to_string())),
        "succ" => Some(MathNode::Operator("≻".to_string())),
        "sim" => Some(MathNode::Operator("∼".to_string())),
        "perp" => Some(MathNode::Operator("⊥".to_string())),
        "preceq" => Some(MathNode::Operator("⪯".to_string())),
        "succeq" => Some(MathNode::Operator("⪰".to_string())),
        "simeq" => Some(MathNode::Operator("≃".to_string())),
        "mid" => Some(MathNode::Operator("∣".to_string())),
        "ll" => Some(MathNode::Operator("≪".to_string())),
        "gg" => Some(MathNode::Operator("≫".to_string())),
        "asymp" => Some(MathNode::Operator("≍".to_string())),
        "parallel" => Some(MathNode::Operator("∥".to_string())),
        "bowtie" => Some(MathNode::Operator("⋈".to_string())),
        "smile" => Some(MathNode::Operator("⌣".to_string())),
        "sqsubseteq" => Some(MathNode::Operator("⊑".to_string())),
        "sqsupseteq" => Some(MathNode::Operator("⊒".to_string())),
        "doteq" => Some(MathNode::Operator("≐".to_string())),
        "frown" => Some(MathNode::Operator("⌢".to_string())),
        "ni" => Some(MathNode::Operator("∋".to_string())),
        "propto" => Some(MathNode::Operator("∝".to_string())),
        "vdash" => Some(MathNode::Operator("⊢".to_string())),
        "dashv" => Some(MathNode::Operator("⊣".to_string())),
        "owns" => Some(MathNode::Operator("∋".to_string())),
        "ldotp" => Some(MathNode::Operator(".".to_string())),
        "cdotp" => Some(MathNode::Operator("⋅".to_string())),
        "aleph" => Some(MathNode::Identifier("ℵ".to_string())),
        "forall" => Some(MathNode::Identifier("∀".to_string())),
        "hbar" => Some(MathNode::Identifier("ℏ".to_string())),
        "exists" => Some(MathNode::Identifier("∃".to_string())),
        "nabla" => Some(MathNode::Identifier("∇".to_string())),
        "flat" => Some(MathNode::Identifier("♭".to_string())),
        "ell" => Some(MathNode::Identifier("ℓ".to_string())),
        "natural" => Some(MathNode::Identifier("♮".to_string())),
        "clubsuit" => Some(MathNode::Identifier("♣".to_string())),
        "wp" => Some(MathNode::Identifier("℘".to_string())),
        "sharp" => Some(MathNode::Identifier("♯".to_string())),
        "diamondsuit" => Some(MathNode::Identifier("♢".to_string())),
        "Re" => Some(MathNode::Identifier("ℜ".to_string())),
        "heartsuit" => Some(MathNode::Identifier("♡".to_string())),
        "Im" => Some(MathNode::Identifier("ℑ".to_string())),
        "spadesuit" => Some(MathNode::Identifier("♠".to_string())),
        "S" => Some(MathNode::Identifier("§".to_string())),
        "P" => Some(MathNode::Identifier("¶".to_string())),
        "dag" => Some(MathNode::Identifier("†".to_string())),
        "ddag" => Some(MathNode::Identifier("‡".to_string())),
        "rmoustache" => Some(MathNode::Operator("⎱".to_string())),
        "lmoustache" => Some(MathNode::Operator("⎰".to_string())),
        "rgroup" => Some(MathNode::Operator("⟯".to_string())),
        "lgroup" => Some(MathNode::Operator("⟮".to_string())),
        "mp" => Some(MathNode::Operator("∓".to_string())),
        "ominus" => Some(MathNode::Operator("⊖".to_string())),
        "uplus" => Some(MathNode::Operator("⊎".to_string())),
        "sqcap" => Some(MathNode::Operator("⊓".to_string())),
        "ast" => Some(MathNode::Operator("∗".to_string())),
        "sqcup" => Some(MathNode::Operator("⊔".to_string())),
        "bigcirc" => Some(MathNode::Operator("◯".to_string())),
        "bullet" => Some(MathNode::Operator("∙".to_string())),
        "ddagger" => Some(MathNode::Operator("‡".to_string())),
        "wr" => Some(MathNode::Operator("≀".to_string())),
        "amalg" => Some(MathNode::Operator("⨿".to_string())),
        "And" => Some(MathNode::Operator("&".to_string())),
        "longleftarrow" => Some(MathNode::Operator("⟵".to_string())),
        "Leftarrow" => Some(MathNode::Operator("⇐".to_string())),
        "Longleftarrow" => Some(MathNode::Operator("⟸".to_string())),
        "longrightarrow" => Some(MathNode::Operator("⟶".to_string())),
        "Rightarrow" => Some(MathNode::Operator("⇒".to_string())),
        "Longrightarrow" => Some(MathNode::Operator("⟹".to_string())),
        "leftrightarrow" => Some(MathNode::Operator("↔".to_string())),
        "longleftrightarrow" => Some(MathNode::Operator("⟷".to_string())),
        "Leftrightarrow" => Some(MathNode::Operator("⇔".to_string())),
        "Longleftrightarrow" => Some(MathNode::Operator("⟺".to_string())),
        "mapsto" => Some(MathNode::Operator("↦".to_string())),
        "longmapsto" => Some(MathNode::Operator("⟼".to_string())),
        "nearrow" => Some(MathNode::Operator("↗".to_string())),
        "hookleftarrow" => Some(MathNode::Operator("↩".to_string())),
        "hookrightarrow" => Some(MathNode::Operator("↪".to_string())),
        "searrow" => Some(MathNode::Operator("↘".to_string())),
        "leftharpoonup" => Some(MathNode::Operator("↼".to_string())),
        "rightharpoonup" => Some(MathNode::Operator("⇀".to_string())),
        "swarrow" => Some(MathNode::Operator("↙".to_string())),
        "leftharpoondown" => Some(MathNode::Operator("↽".to_string())),
        "rightharpoondown" => Some(MathNode::Operator("⇁".to_string())),
        "nwarrow" => Some(MathNode::Operator("↖".to_string())),
        "rightleftharpoons" => Some(MathNode::Operator("⇌".to_string())),
        "nless" => Some(MathNode::Operator("≮".to_string())),
        "lneq" => Some(MathNode::Operator("⪇".to_string())),
        "lneqq" => Some(MathNode::Operator("≨".to_string())),
        "lnsim" => Some(MathNode::Operator("⋦".to_string())),
        "lnapprox" => Some(MathNode::Operator("⪉".to_string())),
        "nprec" => Some(MathNode::Operator("⊀".to_string())),
        "npreceq" => Some(MathNode::Operator("⋠".to_string())),
        "precnsim" => Some(MathNode::Operator("⋨".to_string())),
        "precnapprox" => Some(MathNode::Operator("⪹".to_string())),
        "nsim" => Some(MathNode::Operator("≁".to_string())),
        "nmid" => Some(MathNode::Operator("∤".to_string())),
        "nvdash" => Some(MathNode::Operator("⊬".to_string())),
        "nvDash" => Some(MathNode::Operator("⊭".to_string())),
        "ntriangleleft" => Some(MathNode::Operator("⋪".to_string())),
        "ntrianglelefteq" => Some(MathNode::Operator("⋬".to_string())),
        "subsetneq" => Some(MathNode::Operator("⊊".to_string())),
        "subsetneqq" => Some(MathNode::Operator("⫋".to_string())),
        "ngtr" => Some(MathNode::Operator("≯".to_string())),
        "gneq" => Some(MathNode::Operator("⪈".to_string())),
        "gneqq" => Some(MathNode::Operator("≩".to_string())),
        "gnsim" => Some(MathNode::Operator("⋧".to_string())),
        "gnapprox" => Some(MathNode::Operator("⪊".to_string())),
        "nsucc" => Some(MathNode::Operator("⊁".to_string())),
        "nsucceq" => Some(MathNode::Operator("⋡".to_string())),
        "succnsim" => Some(MathNode::Operator("⋩".to_string())),
        "succnapprox" => Some(MathNode::Operator("⪺".to_string())),
        "ncong" => Some(MathNode::Operator("≆".to_string())),
        "nparallel" => Some(MathNode::Operator("∦".to_string())),
        "nVDash" => Some(MathNode::Operator("⊯".to_string())),
        "ntriangleright" => Some(MathNode::Operator("⋫".to_string())),
        "ntrianglerighteq" => Some(MathNode::Operator("⋭".to_string())),
        "supsetneq" => Some(MathNode::Operator("⊋".to_string())),
        "supsetneqq" => Some(MathNode::Operator("⫌".to_string())),
        "nVdash" => Some(MathNode::Operator("⊮".to_string())),
        "precneqq" => Some(MathNode::Operator("⪵".to_string())),
        "succneqq" => Some(MathNode::Operator("⪶".to_string())),
        "unlhd" => Some(MathNode::Operator("⊴".to_string())),
        "unrhd" => Some(MathNode::Operator("⊵".to_string())),
        "nleftarrow" => Some(MathNode::Operator("↚".to_string())),
        "nrightarrow" => Some(MathNode::Operator("↛".to_string())),
        "nLeftarrow" => Some(MathNode::Operator("⇍".to_string())),
        "nRightarrow" => Some(MathNode::Operator("⇏".to_string())),
        "nleftrightarrow" => Some(MathNode::Operator("↮".to_string())),
        "nLeftrightarrow" => Some(MathNode::Operator("⇎".to_string())),
        "vartriangle" => Some(MathNode::Operator("△".to_string())),
        "hslash" => Some(MathNode::Identifier("ℏ".to_string())),
        "triangledown" => Some(MathNode::Identifier("▽".to_string())),
        "lozenge" => Some(MathNode::Identifier("◊".to_string())),
        "circledS" => Some(MathNode::Identifier("Ⓢ".to_string())),
        "circledR" => Some(MathNode::Identifier("®".to_string())),
        "measuredangle" => Some(MathNode::Identifier("∡".to_string())),
        "nexists" => Some(MathNode::Identifier("∄".to_string())),
        "mho" => Some(MathNode::Identifier("℧".to_string())),
        "Finv" => Some(MathNode::Identifier("Ⅎ".to_string())),
        "Game" => Some(MathNode::Identifier("⅁".to_string())),
        "backprime" => Some(MathNode::Identifier("‵".to_string())),
        "blacktriangle" => Some(MathNode::Identifier("▲".to_string())),
        "blacktriangledown" => Some(MathNode::Identifier("▼".to_string())),
        "blacksquare" => Some(MathNode::Identifier("■".to_string())),
        "blacklozenge" => Some(MathNode::Identifier("⧫".to_string())),
        "bigstar" => Some(MathNode::Identifier("★".to_string())),
        "sphericalangle" => Some(MathNode::Identifier("∢".to_string())),
        "complement" => Some(MathNode::Identifier("∁".to_string())),
        "eth" => Some(MathNode::Identifier("ð".to_string())),
        "diagup" => Some(MathNode::Identifier("╱".to_string())),
        "diagdown" => Some(MathNode::Identifier("╲".to_string())),
        "square" => Some(MathNode::Identifier("□".to_string())),
        "Box" => Some(MathNode::Identifier("□".to_string())),
        "Diamond" => Some(MathNode::Identifier("◊".to_string())),
        "yen" => Some(MathNode::Identifier("¥".to_string())),
        "checkmark" => Some(MathNode::Identifier("✓".to_string())),
        "beth" => Some(MathNode::Identifier("ℶ".to_string())),
        "daleth" => Some(MathNode::Identifier("ℸ".to_string())),
        "gimel" => Some(MathNode::Identifier("ℷ".to_string())),
        "digamma" => Some(MathNode::Identifier("ϝ".to_string())),
        "varkappa" => Some(MathNode::Identifier("ϰ".to_string())),
        "leqq" => Some(MathNode::Operator("≦".to_string())),
        "leqslant" => Some(MathNode::Operator("⩽".to_string())),
        "eqslantless" => Some(MathNode::Operator("⪕".to_string())),
        "lesssim" => Some(MathNode::Operator("≲".to_string())),
        "lessapprox" => Some(MathNode::Operator("⪅".to_string())),
        "approxeq" => Some(MathNode::Operator("≊".to_string())),
        "lessdot" => Some(MathNode::Operator("⋖".to_string())),
        "lll" => Some(MathNode::Operator("⋘".to_string())),
        "lessgtr" => Some(MathNode::Operator("≶".to_string())),
        "lesseqgtr" => Some(MathNode::Operator("⋚".to_string())),
        "lesseqqgtr" => Some(MathNode::Operator("⪋".to_string())),
        "doteqdot" => Some(MathNode::Operator("≑".to_string())),
        "risingdotseq" => Some(MathNode::Operator("≓".to_string())),
        "fallingdotseq" => Some(MathNode::Operator("≒".to_string())),
        "backsim" => Some(MathNode::Operator("∽".to_string())),
        "backsimeq" => Some(MathNode::Operator("⋍".to_string())),
        "subseteqq" => Some(MathNode::Operator("⫅".to_string())),
        "Subset" => Some(MathNode::Operator("⋐".to_string())),
        "sqsubset" => Some(MathNode::Operator("⊏".to_string())),
        "preccurlyeq" => Some(MathNode::Operator("≼".to_string())),
        "curlyeqprec" => Some(MathNode::Operator("⋞".to_string())),
        "precsim" => Some(MathNode::Operator("≾".to_string())),
        "precapprox" => Some(MathNode::Operator("⪷".to_string())),
        "vartriangleleft" => Some(MathNode::Operator("⊲".to_string())),
        "trianglelefteq" => Some(MathNode::Operator("⊴".to_string())),
        "vDash" => Some(MathNode::Operator("⊨".to_string())),
        "Vvdash" => Some(MathNode::Operator("⊪".to_string())),
        "smallsmile" => Some(MathNode::Operator("⌣".to_string())),
        "smallfrown" => Some(MathNode::Operator("⌢".to_string())),
        "bumpeq" => Some(MathNode::Operator("≏".to_string())),
        "Bumpeq" => Some(MathNode::Operator("≎".to_string())),
        "geqq" => Some(MathNode::Operator("≧".to_string())),
        "geqslant" => Some(MathNode::Operator("⩾".to_string())),
        "eqslantgtr" => Some(MathNode::Operator("⪖".to_string())),
        "gtrsim" => Some(MathNode::Operator("≳".to_string())),
        "gtrapprox" => Some(MathNode::Operator("⪆".to_string())),
        "gtrdot" => Some(MathNode::Operator("⋗".to_string())),
        "ggg" => Some(MathNode::Operator("⋙".to_string())),
        "gtrless" => Some(MathNode::Operator("≷".to_string())),
        "gtreqless" => Some(MathNode::Operator("⋛".to_string())),
        "gtreqqless" => Some(MathNode::Operator("⪌".to_string())),
        "eqcirc" => Some(MathNode::Operator("≖".to_string())),
        "circeq" => Some(MathNode::Operator("≗".to_string())),
        "triangleq" => Some(MathNode::Operator("≜".to_string())),
        "thicksim" => Some(MathNode::Operator("∼".to_string())),
        "thickapprox" => Some(MathNode::Operator("≈".to_string())),
        "supseteqq" => Some(MathNode::Operator("⫆".to_string())),
        "Supset" => Some(MathNode::Operator("⋑".to_string())),
        "sqsupset" => Some(MathNode::Operator("⊐".to_string())),
        "succcurlyeq" => Some(MathNode::Operator("≽".to_string())),
        "curlyeqsucc" => Some(MathNode::Operator("⋟".to_string())),
        "succsim" => Some(MathNode::Operator("≿".to_string())),
        "succapprox" => Some(MathNode::Operator("⪸".to_string())),
        "vartriangleright" => Some(MathNode::Operator("⊳".to_string())),
        "trianglerighteq" => Some(MathNode::Operator("⊵".to_string())),
        "Vdash" => Some(MathNode::Operator("⊩".to_string())),
        "shortmid" => Some(MathNode::Operator("∣".to_string())),
        "shortparallel" => Some(MathNode::Operator("∥".to_string())),
        "between" => Some(MathNode::Operator("≬".to_string())),
        "pitchfork" => Some(MathNode::Operator("⋔".to_string())),
        "varpropto" => Some(MathNode::Operator("∝".to_string())),
        "blacktriangleleft" => Some(MathNode::Operator("◀".to_string())),
        "therefore" => Some(MathNode::Operator("∴".to_string())),
        "backepsilon" => Some(MathNode::Operator("∍".to_string())),
        "blacktriangleright" => Some(MathNode::Operator("▶".to_string())),
        "because" => Some(MathNode::Operator("∵".to_string())),
        "llless" => Some(MathNode::Operator("⋘".to_string())),
        "gggtr" => Some(MathNode::Operator("⋙".to_string())),
        "lhd" => Some(MathNode::Operator("⊲".to_string())),
        "rhd" => Some(MathNode::Operator("⊳".to_string())),
        "eqsim" => Some(MathNode::Operator("≂".to_string())),
        "Join" => Some(MathNode::Operator("⋈".to_string())),
        "Doteq" => Some(MathNode::Operator("≑".to_string())),
        "dotplus" => Some(MathNode::Operator("∔".to_string())),
        "smallsetminus" => Some(MathNode::Operator("∖".to_string())),
        "Cap" => Some(MathNode::Operator("⋒".to_string())),
        "Cup" => Some(MathNode::Operator("⋓".to_string())),
        "doublebarwedge" => Some(MathNode::Operator("⩞".to_string())),
        "boxminus" => Some(MathNode::Operator("⊟".to_string())),
        "boxplus" => Some(MathNode::Operator("⊞".to_string())),
        "divideontimes" => Some(MathNode::Operator("⋇".to_string())),
        "ltimes" => Some(MathNode::Operator("⋉".to_string())),
        "rtimes" => Some(MathNode::Operator("⋊".to_string())),
        "leftthreetimes" => Some(MathNode::Operator("⋋".to_string())),
        "rightthreetimes" => Some(MathNode::Operator("⋌".to_string())),
        "curlywedge" => Some(MathNode::Operator("⋏".to_string())),
        "curlyvee" => Some(MathNode::Operator("⋎".to_string())),
        "circleddash" => Some(MathNode::Operator("⊝".to_string())),
        "circledast" => Some(MathNode::Operator("⊛".to_string())),
        "centerdot" => Some(MathNode::Operator("⋅".to_string())),
        "intercal" => Some(MathNode::Operator("⊺".to_string())),
        "doublecap" => Some(MathNode::Operator("⋒".to_string())),
        "doublecup" => Some(MathNode::Operator("⋓".to_string())),
        "boxtimes" => Some(MathNode::Operator("⊠".to_string())),
        "dashrightarrow" => Some(MathNode::Operator("⇢".to_string())),
        "dashleftarrow" => Some(MathNode::Operator("⇠".to_string())),
        "leftleftarrows" => Some(MathNode::Operator("⇇".to_string())),
        "leftrightarrows" => Some(MathNode::Operator("⇆".to_string())),
        "Lleftarrow" => Some(MathNode::Operator("⇚".to_string())),
        "twoheadleftarrow" => Some(MathNode::Operator("↞".to_string())),
        "leftarrowtail" => Some(MathNode::Operator("↢".to_string())),
        "looparrowleft" => Some(MathNode::Operator("↫".to_string())),
        "leftrightharpoons" => Some(MathNode::Operator("⇋".to_string())),
        "curvearrowleft" => Some(MathNode::Operator("↶".to_string())),
        "circlearrowleft" => Some(MathNode::Operator("↺".to_string())),
        "Lsh" => Some(MathNode::Operator("↰".to_string())),
        "upuparrows" => Some(MathNode::Operator("⇈".to_string())),
        "upharpoonleft" => Some(MathNode::Operator("↿".to_string())),
        "downharpoonleft" => Some(MathNode::Operator("⇃".to_string())),
        "origof" => Some(MathNode::Operator("⊶".to_string())),
        "imageof" => Some(MathNode::Operator("⊷".to_string())),
        "multimap" => Some(MathNode::Operator("⊸".to_string())),
        "leftrightsquigarrow" => Some(MathNode::Operator("↭".to_string())),
        "rightrightarrows" => Some(MathNode::Operator("⇉".to_string())),
        "rightleftarrows" => Some(MathNode::Operator("⇄".to_string())),
        "twoheadrightarrow" => Some(MathNode::Operator("↠".to_string())),
        "rightarrowtail" => Some(MathNode::Operator("↣".to_string())),
        "looparrowright" => Some(MathNode::Operator("↬".to_string())),
        "curvearrowright" => Some(MathNode::Operator("↷".to_string())),
        "circlearrowright" => Some(MathNode::Operator("↻".to_string())),
        "Rsh" => Some(MathNode::Operator("↱".to_string())),
        "downdownarrows" => Some(MathNode::Operator("⇊".to_string())),
        "upharpoonright" => Some(MathNode::Operator("↾".to_string())),
        "downharpoonright" => Some(MathNode::Operator("⇂".to_string())),
        "rightsquigarrow" => Some(MathNode::Operator("⇝".to_string())),
        "leadsto" => Some(MathNode::Operator("⇝".to_string())),
        "Rrightarrow" => Some(MathNode::Operator("⇛".to_string())),
        "restriction" => Some(MathNode::Operator("↾".to_string())),
        "angle" => Some(MathNode::Identifier("∠".to_string())),
        "infty" => Some(MathNode::Identifier("∞".to_string())),
        "prime" => Some(MathNode::Identifier("′".to_string())),
        "triangle" => Some(MathNode::Identifier("△".to_string())),
        "Gamma" => Some(MathNode::Identifier("Γ".to_string())),
        "Delta" => Some(MathNode::Identifier("Δ".to_string())),
        "Theta" => Some(MathNode::Identifier("Θ".to_string())),
        "Lambda" => Some(MathNode::Identifier("Λ".to_string())),
        "Xi" => Some(MathNode::Identifier("Ξ".to_string())),
        "Pi" => Some(MathNode::Identifier("Π".to_string())),
        "Sigma" => Some(MathNode::Identifier("Σ".to_string())),
        "Upsilon" => Some(MathNode::Identifier("Υ".to_string())),
        "Phi" => Some(MathNode::Identifier("Φ".to_string())),
        "Psi" => Some(MathNode::Identifier("Ψ".to_string())),
        "Omega" => Some(MathNode::Identifier("Ω".to_string())),
        "neg" => Some(MathNode::Identifier("¬".to_string())),
        "lnot" => Some(MathNode::Identifier("¬".to_string())),
        "top" => Some(MathNode::Identifier("⊤".to_string())),
        "bot" => Some(MathNode::Identifier("⊥".to_string())),
        "emptyset" => Some(MathNode::Identifier("∅".to_string())),
        "varnothing" => Some(MathNode::Identifier("∅".to_string())),
        "alpha" => Some(MathNode::Identifier("α".to_string())),
        "beta" => Some(MathNode::Identifier("β".to_string())),
        "gamma" => Some(MathNode::Identifier("γ".to_string())),
        "delta" => Some(MathNode::Identifier("δ".to_string())),
        "epsilon" => Some(MathNode::Identifier("ϵ".to_string())),
        "zeta" => Some(MathNode::Identifier("ζ".to_string())),
        "eta" => Some(MathNode::Identifier("η".to_string())),
        "theta" => Some(MathNode::Identifier("θ".to_string())),
        "iota" => Some(MathNode::Identifier("ι".to_string())),
        "kappa" => Some(MathNode::Identifier("κ".to_string())),
        "lambda" => Some(MathNode::Identifier("λ".to_string())),
        "mu" => Some(MathNode::Identifier("μ".to_string())),
        "nu" => Some(MathNode::Identifier("ν".to_string())),
        "xi" => Some(MathNode::Identifier("ξ".to_string())),
        "omicron" => Some(MathNode::Identifier("ο".to_string())),
        "pi" => Some(MathNode::Identifier("π".to_string())),
        "rho" => Some(MathNode::Identifier("ρ".to_string())),
        "sigma" => Some(MathNode::Identifier("σ".to_string())),
        "tau" => Some(MathNode::Identifier("τ".to_string())),
        "upsilon" => Some(MathNode::Identifier("υ".to_string())),
        "phi" => Some(MathNode::Identifier("ϕ".to_string())),
        "chi" => Some(MathNode::Identifier("χ".to_string())),
        "psi" => Some(MathNode::Identifier("ψ".to_string())),
        "omega" => Some(MathNode::Identifier("ω".to_string())),
        "varepsilon" => Some(MathNode::Identifier("ε".to_string())),
        "vartheta" => Some(MathNode::Identifier("ϑ".to_string())),
        "varpi" => Some(MathNode::Identifier("ϖ".to_string())),
        "varrho" => Some(MathNode::Identifier("ϱ".to_string())),
        "varsigma" => Some(MathNode::Identifier("ς".to_string())),
        "varphi" => Some(MathNode::Identifier("φ".to_string())),
        "cdot" => Some(MathNode::Operator("⋅".to_string())),
        "circ" => Some(MathNode::Operator("∘".to_string())),
        "div" => Some(MathNode::Operator("÷".to_string())),
        "pm" => Some(MathNode::Operator("±".to_string())),
        "times" => Some(MathNode::Operator("×".to_string())),
        "cap" => Some(MathNode::Operator("∩".to_string())),
        "cup" => Some(MathNode::Operator("∪".to_string())),
        "setminus" => Some(MathNode::Operator("∖".to_string())),
        "land" => Some(MathNode::Operator("∧".to_string())),
        "lor" => Some(MathNode::Operator("∨".to_string())),
        "wedge" => Some(MathNode::Operator("∧".to_string())),
        "vee" => Some(MathNode::Operator("∨".to_string())),
        "surd" => Some(MathNode::Identifier("√".to_string())),
        "langle" => Some(MathNode::Operator("⟨".to_string())),
        "lvert" => Some(MathNode::Operator("∣".to_string())),
        "lVert" => Some(MathNode::Operator("∥".to_string())),
        "rangle" => Some(MathNode::Operator("⟩".to_string())),
        "rvert" => Some(MathNode::Operator("∣".to_string())),
        "rVert" => Some(MathNode::Operator("∥".to_string())),
        "approx" => Some(MathNode::Operator("≈".to_string())),
        "cong" => Some(MathNode::Operator("≅".to_string())),
        "ge" => Some(MathNode::Operator("≥".to_string())),
        "geq" => Some(MathNode::Operator("≥".to_string())),
        "gets" => Some(MathNode::Operator("←".to_string())),
        "gt" => Some(MathNode::Operator(">".to_string())),
        "in" => Some(MathNode::Operator("∈".to_string())),
        "subset" => Some(MathNode::Operator("⊂".to_string())),
        "supset" => Some(MathNode::Operator("⊃".to_string())),
        "subseteq" => Some(MathNode::Operator("⊆".to_string())),
        "supseteq" => Some(MathNode::Operator("⊇".to_string())),
        "nsubseteq" => Some(MathNode::Operator("⊈".to_string())),
        "nsupseteq" => Some(MathNode::Operator("⊉".to_string())),
        "models" => Some(MathNode::Operator("⊨".to_string())),
        "leftarrow" => Some(MathNode::Operator("←".to_string())),
        "le" => Some(MathNode::Operator("≤".to_string())),
        "leq" => Some(MathNode::Operator("≤".to_string())),
        "lt" => Some(MathNode::Operator("<".to_string())),
        "rightarrow" => Some(MathNode::Operator("→".to_string())),
        "to" => Some(MathNode::Operator("→".to_string())),
        "ngeq" => Some(MathNode::Operator("≱".to_string())),
        "nleq" => Some(MathNode::Operator("≰".to_string())),
        "space" => Some(MathNode::Operator(" ".to_string())),
        "nobreakspace" => Some(MathNode::Operator(" ".to_string())),
        "barwedge" => Some(MathNode::Operator("⊼".to_string())),
        "veebar" => Some(MathNode::Operator("⊻".to_string())),
        "odot" => Some(MathNode::Operator("⊙".to_string())),
        "oplus" => Some(MathNode::Operator("⊕".to_string())),
        "otimes" => Some(MathNode::Operator("⊗".to_string())),
        "partial" => Some(MathNode::Identifier("∂".to_string())),
        "oslash" => Some(MathNode::Operator("⊘".to_string())),
        "circledcirc" => Some(MathNode::Operator("⊚".to_string())),
        "boxdot" => Some(MathNode::Operator("⊡".to_string())),
        "bigtriangleup" => Some(MathNode::Operator("△".to_string())),
        "bigtriangledown" => Some(MathNode::Operator("▽".to_string())),
        "dagger" => Some(MathNode::Operator("†".to_string())),
        "diamond" => Some(MathNode::Operator("⋄".to_string())),
        "star" => Some(MathNode::Operator("⋆".to_string())),
        "triangleleft" => Some(MathNode::Operator("◃".to_string())),
        "triangleright" => Some(MathNode::Operator("▹".to_string())),
        "lbrace" => Some(MathNode::Operator("{".to_string())),
        "rbrace" => Some(MathNode::Operator("}".to_string())),
        "lbrack" => Some(MathNode::Operator("[".to_string())),
        "rbrack" => Some(MathNode::Operator("]".to_string())),
        "lparen" => Some(MathNode::Operator("(".to_string())),
        "rparen" => Some(MathNode::Operator(")".to_string())),
        "lfloor" => Some(MathNode::Operator("⌊".to_string())),
        "rfloor" => Some(MathNode::Operator("⌋".to_string())),
        "lceil" => Some(MathNode::Operator("⌈".to_string())),
        "rceil" => Some(MathNode::Operator("⌉".to_string())),
        "backslash" => Some(MathNode::Identifier("\\".to_string())),
        "vert" => Some(MathNode::Identifier("∣".to_string())),
        "Vert" => Some(MathNode::Identifier("∥".to_string())),
        "uparrow" => Some(MathNode::Operator("↑".to_string())),
        "Uparrow" => Some(MathNode::Operator("⇑".to_string())),
        "downarrow" => Some(MathNode::Operator("↓".to_string())),
        "Downarrow" => Some(MathNode::Operator("⇓".to_string())),
        "updownarrow" => Some(MathNode::Operator("↕".to_string())),
        "Updownarrow" => Some(MathNode::Operator("⇕".to_string())),
        "coprod" => Some(MathNode::Operator("∐".to_string())),
        "bigvee" => Some(MathNode::Operator("⋁".to_string())),
        "bigwedge" => Some(MathNode::Operator("⋀".to_string())),
        "biguplus" => Some(MathNode::Operator("⨄".to_string())),
        "bigcap" => Some(MathNode::Operator("⋂".to_string())),
        "bigcup" => Some(MathNode::Operator("⋃".to_string())),
        "int" => Some(MathNode::Operator("∫".to_string())),
        "intop" => Some(MathNode::Operator("∫".to_string())),
        "iint" => Some(MathNode::Operator("∬".to_string())),
        "iiint" => Some(MathNode::Operator("∭".to_string())),
        "prod" => Some(MathNode::Operator("∏".to_string())),
        "sum" => Some(MathNode::Operator("∑".to_string())),
        "bigotimes" => Some(MathNode::Operator("⨂".to_string())),
        "bigoplus" => Some(MathNode::Operator("⨁".to_string())),
        "bigodot" => Some(MathNode::Operator("⨀".to_string())),
        "oint" => Some(MathNode::Operator("∮".to_string())),
        "oiint" => Some(MathNode::Operator("∯".to_string())),
        "oiiint" => Some(MathNode::Operator("∰".to_string())),
        "bigsqcup" => Some(MathNode::Operator("⨆".to_string())),
        "smallint" => Some(MathNode::Operator("∫".to_string())),
        "mathellipsis" => Some(MathNode::Operator("…".to_string())),
        "ldots" => Some(MathNode::Operator("…".to_string())),
        "ddots" => Some(MathNode::Operator("⋱".to_string())),
        "varvdots" => Some(MathNode::Identifier("⋮".to_string())),
        "acute" => Some(MathNode::Operator("ˊ".to_string())),
        "grave" => Some(MathNode::Operator("ˋ".to_string())),
        "ddot" => Some(MathNode::Operator("¨".to_string())),
        "tilde" => Some(MathNode::Operator("~".to_string())),
        "bar" => Some(MathNode::Operator("ˉ".to_string())),
        "breve" => Some(MathNode::Operator("˘".to_string())),
        "check" => Some(MathNode::Operator("ˇ".to_string())),
        "hat" => Some(MathNode::Operator("^".to_string())),
        "vec" => Some(MathNode::Operator("⃗".to_string())),
        "dot" => Some(MathNode::Operator("˙".to_string())),
        "mathring" => Some(MathNode::Operator("˚".to_string())),
        "degree" => Some(MathNode::Identifier("°".to_string())),
        "pounds" => Some(MathNode::Identifier("£".to_string())),
        "mathsterling" => Some(MathNode::Identifier("£".to_string())),
        "maltese" => Some(MathNode::Identifier("✠".to_string())),
        "#" => Some(MathNode::Identifier("#".to_string())),
        "&" => Some(MathNode::Identifier("&".to_string())),
        "$" => Some(MathNode::Identifier("$".to_string())),
        "%" => Some(MathNode::Identifier("%".to_string())),
        "_" => Some(MathNode::Identifier("_".to_string())),
        " " => Some(MathNode::Operator(" ".to_string())),
        "{" => Some(MathNode::Operator("{".to_string())),
        "}" => Some(MathNode::Operator("}".to_string())),
        "|" => Some(MathNode::Identifier("∥".to_string())),
        "neq" => Some(MathNode::Operator("≠".to_string())),
        "ne" => Some(MathNode::Operator("≠".to_string())),
        "implies" => Some(MathNode::Operator("⟹".to_string())),
        "impliedby" => Some(MathNode::Operator("⟸".to_string())),
        "iff" => Some(MathNode::Operator("⟺".to_string())),
        "cdots" => Some(MathNode::Operator("⋯".to_string())),
        "vdots" => Some(MathNode::Operator("⋮".to_string())),
        "dots" => Some(MathNode::Operator("…".to_string())),
        "dotso" => Some(MathNode::Operator("…".to_string())),
        "dotsc" => Some(MathNode::Operator("…".to_string())),
        "dotsb" => Some(MathNode::Operator("⋯".to_string())),
        "dotsm" => Some(MathNode::Operator("⋯".to_string())),
        "dotsi" => Some(MathNode::Operator("⋯".to_string())),
        "dotsx" => Some(MathNode::Operator("…".to_string())),
        "iddots" => Some(MathNode::Operator("⋰".to_string())),
        "notin" => Some(MathNode::Operator("∉".to_string())),
        "notni" => Some(MathNode::Operator("∌".to_string())),
        "coloneqq" => Some(MathNode::Operator("≔".to_string())),
        "eqqcolon" => Some(MathNode::Operator("≕".to_string())),
        "colonequals" => Some(MathNode::Operator("≔".to_string())),
        "equalscolon" => Some(MathNode::Operator("≕".to_string())),
        "darr" => Some(MathNode::Operator("↓".to_string())),
        "dArr" => Some(MathNode::Operator("⇓".to_string())),
        "Darr" => Some(MathNode::Operator("⇓".to_string())),
        "lang" => Some(MathNode::Operator("⟨".to_string())),
        "rang" => Some(MathNode::Operator("⟩".to_string())),
        "uarr" => Some(MathNode::Operator("↑".to_string())),
        "uArr" => Some(MathNode::Operator("⇑".to_string())),
        "Uarr" => Some(MathNode::Operator("⇑".to_string())),
        "alef" => Some(MathNode::Identifier("ℵ".to_string())),
        "alefsym" => Some(MathNode::Identifier("ℵ".to_string())),
        "bull" => Some(MathNode::Operator("∙".to_string())),
        "clubs" => Some(MathNode::Identifier("♣".to_string())),
        "Dagger" => Some(MathNode::Operator("‡".to_string())),
        "diamonds" => Some(MathNode::Identifier("♢".to_string())),
        "empty" => Some(MathNode::Identifier("∅".to_string())),
        "exist" => Some(MathNode::Identifier("∃".to_string())),
        "harr" => Some(MathNode::Operator("↔".to_string())),
        "hArr" => Some(MathNode::Operator("⇔".to_string())),
        "Harr" => Some(MathNode::Operator("⇔".to_string())),
        "hearts" => Some(MathNode::Identifier("♡".to_string())),
        "image" => Some(MathNode::Identifier("ℑ".to_string())),
        "infin" => Some(MathNode::Identifier("∞".to_string())),
        "isin" => Some(MathNode::Operator("∈".to_string())),
        "larr" => Some(MathNode::Operator("←".to_string())),
        "lArr" => Some(MathNode::Operator("⇐".to_string())),
        "Larr" => Some(MathNode::Operator("⇐".to_string())),
        "lrarr" => Some(MathNode::Operator("↔".to_string())),
        "lrArr" => Some(MathNode::Operator("⇔".to_string())),
        "Lrarr" => Some(MathNode::Operator("⇔".to_string())),
        "plusmn" => Some(MathNode::Operator("±".to_string())),
        "rarr" => Some(MathNode::Operator("→".to_string())),
        "rArr" => Some(MathNode::Operator("⇒".to_string())),
        "Rarr" => Some(MathNode::Operator("⇒".to_string())),
        "real" => Some(MathNode::Identifier("ℜ".to_string())),
        "sdot" => Some(MathNode::Operator("⋅".to_string())),
        "sect" => Some(MathNode::Identifier("§".to_string())),
        "spades" => Some(MathNode::Identifier("♠".to_string())),
        "sub" => Some(MathNode::Operator("⊂".to_string())),
        "sube" => Some(MathNode::Operator("⊆".to_string())),
        "supe" => Some(MathNode::Operator("⊇".to_string())),
        "thetasym" => Some(MathNode::Identifier("ϑ".to_string())),
        "weierp" => Some(MathNode::Identifier("℘".to_string())),
        "mathdollar" => Some(MathNode::Identifier("$".to_string())), // base
        "slash" => Some(MathNode::Identifier("/".to_string())),      // base
        "imath" => Some(MathNode::Identifier("ı".to_string())),      // base
        "jmath" => Some(MathNode::Identifier("ȷ".to_string())),      // base
        "overleftarrow" => Some(MathNode::Identifier("⃖".to_string())), // base
        "underleftarrow" => Some(MathNode::Identifier("⃮".to_string())), // amsmath
        "underrightarrow" => Some(MathNode::Identifier("⃯".to_string())), // amsmath
        "iiiint" => Some(MathNode::Operator("⨌".to_string())),       // amsmath
        "widehat" => Some(MathNode::Identifier("̂".to_string())),     // amssymb
        "Bbbk" => Some(MathNode::Identifier("𝕜".to_string())),       // amssymb
        "second" => Some(MathNode::Identifier("″".to_string())),     // mathabx
        "third" => Some(MathNode::Identifier("‴".to_string())),      // mathabx
        "fourth" => Some(MathNode::Identifier("⁗".to_string())),     // mathabx
        "dlsh" => Some(MathNode::Operator("↲".to_string())),         // mathabx
        "drsh" => Some(MathNode::Operator("↳".to_string())),         // mathabx
        "updownarrows" => Some(MathNode::Operator("⇅".to_string())), // mathabx
        "leftsquigarrow" => Some(MathNode::Operator("⇜".to_string())), // mathabx
        "downuparrows" => Some(MathNode::Operator("⇵".to_string())), // mathabx
        "coloneq" => Some(MathNode::Operator("≔".to_string())),      // mathabx
        "corresponds" => Some(MathNode::Operator("≙".to_string())),  // mathabx
        "notasymp" => Some(MathNode::Operator("≭".to_string())),     // mathabx
        "VDash" => Some(MathNode::Operator("⊫".to_string())),        // mathabx
        "hash" => Some(MathNode::Operator("⋕".to_string())),         // mathabx
        "barin" => Some(MathNode::Operator("⋶".to_string())),        // mathabx
        "diameter" => Some(MathNode::Identifier("⌀".to_string())),   // mathabx
        "blacktriangleup" => Some(MathNode::Operator("▴".to_string())), // mathabx
        "smalltriangleup" => Some(MathNode::Operator("▵".to_string())), // mathabx
        "smalltriangleright" => Some(MathNode::Operator("▹".to_string())), // mathabx
        "smalltriangledown" => Some(MathNode::Operator("▿".to_string())), // mathabx
        "smalltriangleleft" => Some(MathNode::Operator("◃".to_string())), // mathabx
        "Sun" => Some(MathNode::Identifier("☉".to_string())),        // mathabx
        "Mercury" => Some(MathNode::Identifier("☿".to_string())),    // mathabx
        "Venus" => Some(MathNode::Identifier("♀".to_string())),      // mathabx
        "varEarth" => Some(MathNode::Identifier("♁".to_string())),   // mathabx
        "Mars" => Some(MathNode::Identifier("♂".to_string())),       // mathabx
        "Jupiter" => Some(MathNode::Identifier("♃".to_string())),    // mathabx
        "Saturn" => Some(MathNode::Identifier("♄".to_string())),     // mathabx
        "Uranus" => Some(MathNode::Identifier("♅".to_string())),     // mathabx
        "Neptune" => Some(MathNode::Identifier("♆".to_string())),    // mathabx
        "Pluto" => Some(MathNode::Identifier("♇".to_string())),      // mathabx
        "Aries" => Some(MathNode::Identifier("♈".to_string())),     // mathabx
        "Taurus" => Some(MathNode::Identifier("♉".to_string())),    // mathabx
        "Gemini" => Some(MathNode::Identifier("♊".to_string())),    // mathabx
        "Leo" => Some(MathNode::Identifier("♌".to_string())),       // mathabx
        "Libra" => Some(MathNode::Identifier("♎".to_string())),     // mathabx
        "Scorpio" => Some(MathNode::Identifier("♏".to_string())),   // mathabx
        "leftrightharpoon" => Some(MathNode::Operator("⥊".to_string())), // mathabx
        "rightleftharpoon" => Some(MathNode::Operator("⥋".to_string())), // mathabx
        "leftleftharpoons" => Some(MathNode::Operator("⥢".to_string())), // mathabx
        "upupharpoons" => Some(MathNode::Operator("⥣".to_string())), // mathabx
        "rightrightharpoons" => Some(MathNode::Operator("⥤".to_string())), // mathabx
        "downdownharpoons" => Some(MathNode::Operator("⥥".to_string())), // mathabx
        "leftbarharpoon" => Some(MathNode::Operator("⥪".to_string())), // mathabx
        "barleftharpoon" => Some(MathNode::Operator("⥫".to_string())), // mathabx
        "rightbarharpoon" => Some(MathNode::Operator("⥬".to_string())), // mathabx
        "barrightharpoon" => Some(MathNode::Operator("⥭".to_string())), // mathabx
        "updownharpoons" => Some(MathNode::Operator("⥮".to_string())), // mathabx
        "downupharpoons" => Some(MathNode::Operator("⥯".to_string())), // mathabx
        "llcurly" => Some(MathNode::Operator("⪻".to_string())),      // mathabx
        "ggcurly" => Some(MathNode::Operator("⪼".to_string())),      // mathabx
        "mathcent" => Some(MathNode::Identifier("¢".to_string())),   // txfonts
        "invamp" => Some(MathNode::Operator("⅋".to_string())),       // txfonts
        "Nwarrow" => Some(MathNode::Operator("⇖".to_string())),      // txfonts
        "Nearrow" => Some(MathNode::Operator("⇗".to_string())),      // txfonts
        "Searrow" => Some(MathNode::Operator("⇘".to_string())),      // txfonts
        "Swarrow" => Some(MathNode::Operator("⇙".to_string())),      // txfonts
        "eqcolon" => Some(MathNode::Operator("∹".to_string())),      // txfonts
        "nsimeq" => Some(MathNode::Operator("≄".to_string())),       // txfonts
        "multimapdotbothA" => Some(MathNode::Operator("⊶".to_string())), // txfonts
        "multimapdotbothB" => Some(MathNode::Operator("⊷".to_string())), // txfonts
        "lrtimes" => Some(MathNode::Operator("⋈".to_string())),      // txfonts
        "Diamondblack" => Some(MathNode::Identifier("◆".to_string())), // txfonts
        "varspadesuit" => Some(MathNode::Identifier("♤".to_string())), // txfonts
        "varheartsuit" => Some(MathNode::Identifier("♥".to_string())), // txfonts
        "vardiamondsuit" => Some(MathNode::Identifier("♦".to_string())), // txfonts
        "varclubsuit" => Some(MathNode::Identifier("♧".to_string())), // txfonts
        "medcirc" => Some(MathNode::Identifier("⚪".to_string())),   // txfonts
        "medbullet" => Some(MathNode::Identifier("⚫".to_string())), // txfonts
        "Diamonddot" => Some(MathNode::Identifier("⟐".to_string())), // txfonts
        "multimapinv" => Some(MathNode::Operator("⟜".to_string())),  // txfonts
        "strictfi" => Some(MathNode::Operator("⥼".to_string())),     // txfonts
        "strictif" => Some(MathNode::Operator("⥽".to_string())),     // txfonts
        "circledbslash" => Some(MathNode::Operator("⦸".to_string())), // txfonts
        "circledless" => Some(MathNode::Operator("⧀".to_string())),  // txfonts
        "circledgtr" => Some(MathNode::Operator("⧁".to_string())),   // txfonts
        "multimapboth" => Some(MathNode::Operator("⧟".to_string())), // txfonts
        "bigsqcap" => Some(MathNode::Operator("⨅".to_string())),     // txfonts
        "varprod" => Some(MathNode::Operator("⨉".to_string())),      // txfonts
        "Coloneqq" => Some(MathNode::Operator("⩴".to_string())),     // txfonts
        "preceqq" => Some(MathNode::Operator("⪳".to_string())),      // txfonts
        "succeqq" => Some(MathNode::Operator("⪴".to_string())),      // txfonts
        "Top" => Some(MathNode::Operator("⫪".to_string())),          // txfonts
        "Bot" => Some(MathNode::Operator("⫫".to_string())),          // txfonts
        "Perp" => Some(MathNode::Operator("⫫".to_string())),         // txfonts
        "varparallel" => Some(MathNode::Operator("⫽".to_string())),  // txfonts
        "binampersand" => Some(MathNode::Identifier("&".to_string())), // stmaryrd
        "Yup" => Some(MathNode::Identifier("⅄".to_string())),        // stmaryrd
        "bindnasrepma" => Some(MathNode::Operator("⅋".to_string())), // stmaryrd
        "mapsfrom" => Some(MathNode::Operator("↤".to_string())),     // stmaryrd
        "lightning" => Some(MathNode::Operator("↯".to_string())),    // stmaryrd
        "leftarrowtriangle" => Some(MathNode::Operator("⇽".to_string())), // stmaryrd
        "rightarrowtriangle" => Some(MathNode::Operator("⇾".to_string())), // stmaryrd
        "boxbar" => Some(MathNode::Operator("◫".to_string())),       // stmaryrd
        "Lbag" => Some(MathNode::Operator("⟅".to_string())),         // stmaryrd
        "Rbag" => Some(MathNode::Operator("⟆".to_string())),         // stmaryrd
        "llbracket" => Some(MathNode::Operator("⟦".to_string())),    // stmaryrd
        "rrbracket" => Some(MathNode::Operator("⟧".to_string())),    // stmaryrd
        "longmapsfrom" => Some(MathNode::Operator("⟻".to_string())), // stmaryrd
        "Longmapsfrom" => Some(MathNode::Operator("⟽".to_string())), // stmaryrd
        "Longmapsto" => Some(MathNode::Operator("⟾".to_string())),   // stmaryrd
        "Mapsfrom" => Some(MathNode::Operator("⤆".to_string())),     // stmaryrd
        "Mapsto" => Some(MathNode::Operator("⤇".to_string())),       // stmaryrd
        "llparenthesis" => Some(MathNode::Operator("⦇".to_string())), // stmaryrd
        "rrparenthesis" => Some(MathNode::Operator("⦈".to_string())), // stmaryrd
        "boxslash" => Some(MathNode::Operator("⧄".to_string())),     // stmaryrd
        "boxbslash" => Some(MathNode::Operator("⧅".to_string())),    // stmaryrd
        "boxast" => Some(MathNode::Operator("⧆".to_string())),       // stmaryrd
        "boxcircle" => Some(MathNode::Operator("⧇".to_string())),    // stmaryrd
        "boxbox" => Some(MathNode::Operator("⧈".to_string())),       // stmaryrd
        "leftslice" => Some(MathNode::Operator("⪦".to_string())),    // stmaryrd
        "rightslice" => Some(MathNode::Operator("⪧".to_string())),   // stmaryrd
        "interleave" => Some(MathNode::Operator("⫴".to_string())),   // stmaryrd
        "biginterleave" => Some(MathNode::Operator("⫼".to_string())), // stmaryrd
        "sslash" => Some(MathNode::Operator("⫽".to_string())),       // stmaryrd
        "talloblong" => Some(MathNode::Operator("⫾".to_string())),   // stmaryrd
        "cat" => Some(MathNode::Operator("⁀".to_string())),          // oz
        "rel" => Some(MathNode::Operator("↔".to_string())),          // oz
        "tsur" => Some(MathNode::Operator("↠".to_string())),         // oz
        "tinj" => Some(MathNode::Operator("↣".to_string())),         // oz
        "pfun" => Some(MathNode::Operator("⇸".to_string())),         // oz
        "ffun" => Some(MathNode::Operator("⇻".to_string())),         // oz
        "exi" => Some(MathNode::Identifier("∃".to_string())),        // oz
        "nexi" => Some(MathNode::Identifier("∄".to_string())),       // oz
        "sdef" => Some(MathNode::Operator("≙".to_string())),         // oz
        "varsdef" => Some(MathNode::Operator("≜".to_string())),      // oz
        "buni" => Some(MathNode::Operator("⊎".to_string())),         // oz
        "dint" => Some(MathNode::Operator("⋂".to_string())),         // oz
        "duni" => Some(MathNode::Operator("⋃".to_string())),         // oz
        "rres" => Some(MathNode::Operator("▷".to_string())),         // oz
        "dres" => Some(MathNode::Operator("◁".to_string())),         // oz
        "psur" => Some(MathNode::Operator("⤀".to_string())),         // oz
        "psurj" => Some(MathNode::Operator("⤀".to_string())),        // oz
        "pinj" => Some(MathNode::Operator("⤔".to_string())),         // oz
        "finj" => Some(MathNode::Operator("⤕".to_string())),         // oz
        "bij" => Some(MathNode::Operator("⤖".to_string())),          // oz
        "spot" => Some(MathNode::Identifier("⦁".to_string())),       // oz
        "limg" => Some(MathNode::Operator("⦇".to_string())),         // oz
        "rimg" => Some(MathNode::Operator("⦈".to_string())),         // oz
        "lblot" => Some(MathNode::Operator("⦉".to_string())),        // oz
        "rblot" => Some(MathNode::Operator("⦊".to_string())),        // oz
        "zhide" => Some(MathNode::Operator("⧹".to_string())),        // oz
        "hide" => Some(MathNode::Operator("⧹".to_string())),         // oz
        "zcmp" => Some(MathNode::Operator("⨟".to_string())),         // oz
        "semi" => Some(MathNode::Operator("⨟".to_string())),         // oz
        "zpipe" => Some(MathNode::Operator("⨠".to_string())),        // oz
        "zproject" => Some(MathNode::Operator("⨡".to_string())),     // oz
        "project" => Some(MathNode::Operator("⨡".to_string())),      // oz
        "fcmp" => Some(MathNode::Operator("⨾".to_string())),         // oz
        "comp" => Some(MathNode::Operator("⨾".to_string())),         // oz
        "dsub" => Some(MathNode::Operator("⩤".to_string())),         // oz
        "ndres" => Some(MathNode::Operator("⩤".to_string())),        // oz
        "rsub" => Some(MathNode::Operator("⩥".to_string())),         // oz
        "nrres" => Some(MathNode::Operator("⩥".to_string())),        // oz
        "exclam" => Some(MathNode::Operator("!".to_string())),       // unicode-math
        "octothorpe" => Some(MathNode::Identifier("#".to_string())), // unicode-math
        "percent" => Some(MathNode::Identifier("%".to_string())),    // unicode-math
        "ampersand" => Some(MathNode::Identifier("&".to_string())),  // unicode-math
        "plus" => Some(MathNode::Operator("+".to_string())),         // unicode-math
        "comma" => Some(MathNode::Operator(",".to_string())),        // unicode-math
        "period" => Some(MathNode::Identifier(".".to_string())),     // unicode-math
        "mathslash" => Some(MathNode::Identifier("/".to_string())),  // unicode-math
        "mathcolon" => Some(MathNode::Operator(":".to_string())),    // unicode-math
        "semicolon" => Some(MathNode::Operator(";".to_string())),    // unicode-math
        "less" => Some(MathNode::Operator("<".to_string())),         // unicode-math
        "equal" => Some(MathNode::Operator("=".to_string())),        // unicode-math
        "greater" => Some(MathNode::Operator(">".to_string())),      // unicode-math
        "question" => Some(MathNode::Identifier("?".to_string())),   // unicode-math
        "atsign" => Some(MathNode::Identifier("@".to_string())),     // unicode-math
        "sphat" => Some(MathNode::Identifier("^".to_string())),      // unicode-math
        "sterling" => Some(MathNode::Identifier("£".to_string())),   // unicode-math
        "matheth" => Some(MathNode::Identifier("ð".to_string())),    // unicode-math
        "Zbar" => Some(MathNode::Identifier("Ƶ".to_string())),       // unicode-math
        "overbar" => Some(MathNode::Identifier("̅".to_string())),     // unicode-math
        "ovhook" => Some(MathNode::Identifier("̉".to_string())),      // unicode-math
        "ocirc" => Some(MathNode::Identifier("̊".to_string())),       // unicode-math
        "candra" => Some(MathNode::Identifier("̐".to_string())),      // unicode-math
        "oturnedcomma" => Some(MathNode::Identifier("̒".to_string())), // unicode-math
        "ocommatopright" => Some(MathNode::Identifier("̕".to_string())), // unicode-math
        "droang" => Some(MathNode::Identifier("̚".to_string())),      // unicode-math
        "wideutilde" => Some(MathNode::Identifier("̰".to_string())),  // unicode-math
        "upAlpha" => Some(MathNode::Identifier("Α".to_string())),    // unicode-math
        "upBeta" => Some(MathNode::Identifier("Β".to_string())),     // unicode-math
        "upGamma" => Some(MathNode::Identifier("Γ".to_string())),    // unicode-math
        "upDelta" => Some(MathNode::Identifier("Δ".to_string())),    // unicode-math
        "upEpsilon" => Some(MathNode::Identifier("Ε".to_string())),  // unicode-math
        "upZeta" => Some(MathNode::Identifier("Ζ".to_string())),     // unicode-math
        "upEta" => Some(MathNode::Identifier("Η".to_string())),      // unicode-math
        "upTheta" => Some(MathNode::Identifier("Θ".to_string())),    // unicode-math
        "upIota" => Some(MathNode::Identifier("Ι".to_string())),     // unicode-math
        "upKappa" => Some(MathNode::Identifier("Κ".to_string())),    // unicode-math
        "upLambda" => Some(MathNode::Identifier("Λ".to_string())),   // unicode-math
        "upMu" => Some(MathNode::Identifier("Μ".to_string())),       // unicode-math
        "upNu" => Some(MathNode::Identifier("Ν".to_string())),       // unicode-math
        "upXi" => Some(MathNode::Identifier("Ξ".to_string())),       // unicode-math
        "upOmicron" => Some(MathNode::Identifier("Ο".to_string())),  // unicode-math
        "upPi" => Some(MathNode::Identifier("Π".to_string())),       // unicode-math
        "upRho" => Some(MathNode::Identifier("Ρ".to_string())),      // unicode-math
        "upSigma" => Some(MathNode::Identifier("Σ".to_string())),    // unicode-math
        "upTau" => Some(MathNode::Identifier("Τ".to_string())),      // unicode-math
        "upUpsilon" => Some(MathNode::Identifier("Υ".to_string())),  // unicode-math
        "upPhi" => Some(MathNode::Identifier("Φ".to_string())),      // unicode-math
        "upChi" => Some(MathNode::Identifier("Χ".to_string())),      // unicode-math
        "upPsi" => Some(MathNode::Identifier("Ψ".to_string())),      // unicode-math
        "upOmega" => Some(MathNode::Identifier("Ω".to_string())),    // unicode-math
        "upalpha" => Some(MathNode::Identifier("α".to_string())),    // unicode-math
        "upbeta" => Some(MathNode::Identifier("β".to_string())),     // unicode-math
        "upgamma" => Some(MathNode::Identifier("γ".to_string())),    // unicode-math
        "updelta" => Some(MathNode::Identifier("δ".to_string())),    // unicode-math
        "upepsilon" => Some(MathNode::Identifier("ε".to_string())),  // unicode-math
        "upzeta" => Some(MathNode::Identifier("ζ".to_string())),     // unicode-math
        "upeta" => Some(MathNode::Identifier("η".to_string())),      // unicode-math
        "uptheta" => Some(MathNode::Identifier("θ".to_string())),    // unicode-math
        "upiota" => Some(MathNode::Identifier("ι".to_string())),     // unicode-math
        "upkappa" => Some(MathNode::Identifier("κ".to_string())),    // unicode-math
        "uplambda" => Some(MathNode::Identifier("λ".to_string())),   // unicode-math
        "upmu" => Some(MathNode::Identifier("μ".to_string())),       // unicode-math
        "upnu" => Some(MathNode::Identifier("ν".to_string())),       // unicode-math
        "upxi" => Some(MathNode::Identifier("ξ".to_string())),       // unicode-math
        "upomicron" => Some(MathNode::Identifier("ο".to_string())),  // unicode-math
        "uppi" => Some(MathNode::Identifier("π".to_string())),       // unicode-math
        "uprho" => Some(MathNode::Identifier("ρ".to_string())),      // unicode-math
        "upvarsigma" => Some(MathNode::Identifier("ς".to_string())), // unicode-math
        "upsigma" => Some(MathNode::Identifier("σ".to_string())),    // unicode-math
        "uptau" => Some(MathNode::Identifier("τ".to_string())),      // unicode-math
        "upupsilon" => Some(MathNode::Identifier("υ".to_string())),  // unicode-math
        "upvarphi" => Some(MathNode::Identifier("φ".to_string())),   // unicode-math
        "upchi" => Some(MathNode::Identifier("χ".to_string())),      // unicode-math
        "uppsi" => Some(MathNode::Identifier("ψ".to_string())),      // unicode-math
        "upomega" => Some(MathNode::Identifier("ω".to_string())),    // unicode-math
        "upvarbeta" => Some(MathNode::Identifier("ϐ".to_string())),  // unicode-math
        "upvartheta" => Some(MathNode::Identifier("ϑ".to_string())), // unicode-math
        "upphi" => Some(MathNode::Identifier("ϕ".to_string())),      // unicode-math
        "upvarpi" => Some(MathNode::Identifier("ϖ".to_string())),    // unicode-math
        "upoldKoppa" => Some(MathNode::Identifier("Ϙ".to_string())), // unicode-math
        "upoldkoppa" => Some(MathNode::Identifier("ϙ".to_string())), // unicode-math
        "upStigma" => Some(MathNode::Identifier("Ϛ".to_string())),   // unicode-math
        "upstigma" => Some(MathNode::Identifier("ϛ".to_string())),   // unicode-math
        "upDigamma" => Some(MathNode::Identifier("Ϝ".to_string())),  // unicode-math
        "updigamma" => Some(MathNode::Identifier("ϝ".to_string())),  // unicode-math
        "upKoppa" => Some(MathNode::Identifier("Ϟ".to_string())),    // unicode-math
        "upkoppa" => Some(MathNode::Identifier("ϟ".to_string())),    // unicode-math
        "upSampi" => Some(MathNode::Identifier("Ϡ".to_string())),    // unicode-math
        "upsampi" => Some(MathNode::Identifier("ϡ".to_string())),    // unicode-math
        "upvarkappa" => Some(MathNode::Identifier("ϰ".to_string())), // unicode-math
        "upvarrho" => Some(MathNode::Identifier("ϱ".to_string())),   // unicode-math
        "upvarTheta" => Some(MathNode::Identifier("ϴ".to_string())), // unicode-math
        "upvarepsilon" => Some(MathNode::Identifier("ϵ".to_string())), // unicode-math
        "upbackepsilon" => Some(MathNode::Identifier("϶".to_string())), // unicode-math
        "horizbar" => Some(MathNode::Identifier("―".to_string())),   // unicode-math
        "twolowline" => Some(MathNode::Identifier("‗".to_string())), // unicode-math
        "smblkcircle" => Some(MathNode::Operator("•".to_string())),  // unicode-math
        "enleadertwodots" => Some(MathNode::Identifier("‥".to_string())), // unicode-math
        "unicodeellipsis" => Some(MathNode::Identifier("…".to_string())), // unicode-math
        "dprime" => Some(MathNode::Identifier("″".to_string())),     // unicode-math
        "trprime" => Some(MathNode::Identifier("‴".to_string())),    // unicode-math
        "backdprime" => Some(MathNode::Identifier("‶".to_string())), // unicode-math
        "backtrprime" => Some(MathNode::Identifier("‷".to_string())), // unicode-math
        "caretinsert" => Some(MathNode::Identifier("‸".to_string())), // unicode-math
        "Exclam" => Some(MathNode::Identifier("‼".to_string())),     // unicode-math
        "tieconcat" => Some(MathNode::Operator("⁀".to_string())),    // unicode-math
        "hyphenbullet" => Some(MathNode::Identifier("⁃".to_string())), // unicode-math
        "fracslash" => Some(MathNode::Operator("⁄".to_string())),    // unicode-math
        "Question" => Some(MathNode::Identifier("⁇".to_string())),   // unicode-math
        "closure" => Some(MathNode::Operator("⁐".to_string())),      // unicode-math
        "qprime" => Some(MathNode::Identifier("⁗".to_string())),     // unicode-math
        "euro" => Some(MathNode::Identifier("€".to_string())),       // unicode-math
        "leftharpoonaccent" => Some(MathNode::Identifier("⃐".to_string())), // unicode-math
        "rightharpoonaccent" => Some(MathNode::Identifier("⃑".to_string())), // unicode-math
        "vertoverlay" => Some(MathNode::Identifier("⃒".to_string())), // unicode-math
        "enclosecircle" => Some(MathNode::Identifier("⃝".to_string())), // unicode-math
        "enclosesquare" => Some(MathNode::Identifier("⃞".to_string())), // unicode-math
        "enclosediamond" => Some(MathNode::Identifier("⃟".to_string())), // unicode-math
        "enclosetriangle" => Some(MathNode::Identifier("⃤".to_string())), // unicode-math
        "annuity" => Some(MathNode::Identifier("⃧".to_string())),     // unicode-math
        "threeunderdot" => Some(MathNode::Identifier("⃨".to_string())), // unicode-math
        "widebridgeabove" => Some(MathNode::Identifier("⃩".to_string())), // unicode-math
        "underleftharpoondown" => Some(MathNode::Identifier("⃭".to_string())), // unicode-math
        "asteraccent" => Some(MathNode::Identifier("⃰".to_string())), // unicode-math
        "BbbC" => Some(MathNode::Identifier("ℂ".to_string())),       // unicode-math
        "Eulerconst" => Some(MathNode::Identifier("ℇ".to_string())), // unicode-math
        "mscrg" => Some(MathNode::Identifier("ℊ".to_string())),      // unicode-math
        "mscrH" => Some(MathNode::Identifier("ℋ".to_string())),      // unicode-math
        "mfrakH" => Some(MathNode::Identifier("ℌ".to_string())),     // unicode-math
        "BbbH" => Some(MathNode::Identifier("ℍ".to_string())),       // unicode-math
        "Planckconst" => Some(MathNode::Identifier("ℎ".to_string())), // unicode-math
        "mscrI" => Some(MathNode::Identifier("ℐ".to_string())),      // unicode-math
        "mscrL" => Some(MathNode::Identifier("ℒ".to_string())),      // unicode-math
        "BbbN" => Some(MathNode::Identifier("ℕ".to_string())),       // unicode-math
        "BbbP" => Some(MathNode::Identifier("ℙ".to_string())),       // unicode-math
        "BbbQ" => Some(MathNode::Identifier("ℚ".to_string())),       // unicode-math
        "mscrR" => Some(MathNode::Identifier("ℛ".to_string())),      // unicode-math
        "BbbR" => Some(MathNode::Identifier("ℝ".to_string())),       // unicode-math
        "BbbZ" => Some(MathNode::Identifier("ℤ".to_string())),       // unicode-math
        "mfrakZ" => Some(MathNode::Identifier("ℨ".to_string())),     // unicode-math
        "turnediota" => Some(MathNode::Identifier("℩".to_string())), // unicode-math
        "Angstrom" => Some(MathNode::Identifier("Å".to_string())),   // unicode-math
        "mscrB" => Some(MathNode::Identifier("ℬ".to_string())),      // unicode-math
        "mfrakC" => Some(MathNode::Identifier("ℭ".to_string())),     // unicode-math
        "mscre" => Some(MathNode::Identifier("ℯ".to_string())),      // unicode-math
        "mscrE" => Some(MathNode::Identifier("ℰ".to_string())),      // unicode-math
        "mscrF" => Some(MathNode::Identifier("ℱ".to_string())),      // unicode-math
        "mscrM" => Some(MathNode::Identifier("ℳ".to_string())),      // unicode-math
        "mscro" => Some(MathNode::Identifier("ℴ".to_string())),      // unicode-math
        "Bbbpi" => Some(MathNode::Identifier("ℼ".to_string())),      // unicode-math
        "Bbbgamma" => Some(MathNode::Identifier("ℽ".to_string())),   // unicode-math
        "BbbGamma" => Some(MathNode::Identifier("ℾ".to_string())),   // unicode-math
        "BbbPi" => Some(MathNode::Identifier("ℿ".to_string())),      // unicode-math
        "Bbbsum" => Some(MathNode::Operator("⅀".to_string())),       // unicode-math
        "sansLturned" => Some(MathNode::Identifier("⅂".to_string())), // unicode-math
        "sansLmirrored" => Some(MathNode::Identifier("⅃".to_string())), // unicode-math
        "mitBbbD" => Some(MathNode::Identifier("ⅅ".to_string())),    // unicode-math
        "mitBbbd" => Some(MathNode::Identifier("ⅆ".to_string())),    // unicode-math
        "mitBbbe" => Some(MathNode::Identifier("ⅇ".to_string())),    // unicode-math
        "mitBbbi" => Some(MathNode::Identifier("ⅈ".to_string())),    // unicode-math
        "mitBbbj" => Some(MathNode::Identifier("ⅉ".to_string())),    // unicode-math
        "PropertyLine" => Some(MathNode::Identifier("⅊".to_string())), // unicode-math
        "upand" => Some(MathNode::Operator("⅋".to_string())),        // unicode-math
        "leftwavearrow" => Some(MathNode::Operator("↜".to_string())), // unicode-math
        "rightwavearrow" => Some(MathNode::Operator("↝".to_string())), // unicode-math
        "twoheaduparrow" => Some(MathNode::Operator("↟".to_string())), // unicode-math
        "twoheaddownarrow" => Some(MathNode::Operator("↡".to_string())), // unicode-math
        "mapsup" => Some(MathNode::Operator("↥".to_string())),       // unicode-math
        "mapsdown" => Some(MathNode::Operator("↧".to_string())),     // unicode-math
        "updownarrowbar" => Some(MathNode::Identifier("↨".to_string())), // unicode-math
        "downzigzagarrow" => Some(MathNode::Operator("↯".to_string())), // unicode-math
        "Ldsh" => Some(MathNode::Operator("↲".to_string())),         // unicode-math
        "Rdsh" => Some(MathNode::Operator("↳".to_string())),         // unicode-math
        "linefeed" => Some(MathNode::Identifier("↴".to_string())),   // unicode-math
        "carriagereturn" => Some(MathNode::Identifier("↵".to_string())), // unicode-math
        "acwopencirclearrow" => Some(MathNode::Identifier("↺".to_string())), // unicode-math
        "cwopencirclearrow" => Some(MathNode::Identifier("↻".to_string())), // unicode-math
        "nHuparrow" => Some(MathNode::Identifier("⇞".to_string())),  // unicode-math
        "nHdownarrow" => Some(MathNode::Identifier("⇟".to_string())), // unicode-math
        "leftdasharrow" => Some(MathNode::Identifier("⇠".to_string())), // unicode-math
        "updasharrow" => Some(MathNode::Identifier("⇡".to_string())), // unicode-math
        "rightdasharrow" => Some(MathNode::Identifier("⇢".to_string())), // unicode-math
        "downdasharrow" => Some(MathNode::Identifier("⇣".to_string())), // unicode-math
        "barleftarrow" => Some(MathNode::Operator("⇤".to_string())), // unicode-math
        "rightarrowbar" => Some(MathNode::Operator("⇥".to_string())), // unicode-math
        "leftwhitearrow" => Some(MathNode::Identifier("⇦".to_string())), // unicode-math
        "upwhitearrow" => Some(MathNode::Identifier("⇧".to_string())), // unicode-math
        "rightwhitearrow" => Some(MathNode::Identifier("⇨".to_string())), // unicode-math
        "downwhitearrow" => Some(MathNode::Identifier("⇩".to_string())), // unicode-math
        "whitearrowupfrombar" => Some(MathNode::Identifier("⇪".to_string())), // unicode-math
        "circleonrightarrow" => Some(MathNode::Operator("⇴".to_string())), // unicode-math
        "rightthreearrows" => Some(MathNode::Operator("⇶".to_string())), // unicode-math
        "nvleftarrow" => Some(MathNode::Operator("⇷".to_string())),  // unicode-math
        "nvrightarrow" => Some(MathNode::Operator("⇸".to_string())), // unicode-math
        "nvleftrightarrow" => Some(MathNode::Operator("⇹".to_string())), // unicode-math
        "nVleftarrow" => Some(MathNode::Operator("⇺".to_string())),  // unicode-math
        "nVrightarrow" => Some(MathNode::Operator("⇻".to_string())), // unicode-math
        "nVleftrightarrow" => Some(MathNode::Operator("⇼".to_string())), // unicode-math
        "increment" => Some(MathNode::Identifier("∆".to_string())),  // unicode-math
        "smallin" => Some(MathNode::Operator("∊".to_string())),      // unicode-math
        "smallni" => Some(MathNode::Operator("∍".to_string())),      // unicode-math
        "minus" => Some(MathNode::Operator("−".to_string())),        // unicode-math
        "divslash" => Some(MathNode::Operator("∕".to_string())),     // unicode-math
        "vysmwhtcircle" => Some(MathNode::Operator("∘".to_string())), // unicode-math
        "vysmblkcircle" => Some(MathNode::Operator("∙".to_string())), // unicode-math
        "intclockwise" => Some(MathNode::Operator("∱".to_string())), // unicode-math
        "mathratio" => Some(MathNode::Operator("∶".to_string())),    // unicode-math
        "Colon" => Some(MathNode::Operator("∷".to_string())),        // unicode-math
        "dotminus" => Some(MathNode::Operator("∸".to_string())),     // unicode-math
        "dashcolon" => Some(MathNode::Operator("∹".to_string())),    // unicode-math
        "dotsminusdots" => Some(MathNode::Operator("∺".to_string())), // unicode-math
        "kernelcontraction" => Some(MathNode::Operator("∻".to_string())), // unicode-math
        "invlazys" => Some(MathNode::Operator("∾".to_string())),     // unicode-math
        "sinewave" => Some(MathNode::Identifier("∿".to_string())),   // unicode-math
        "nsime" => Some(MathNode::Operator("≄".to_string())),        // unicode-math
        "simneqq" => Some(MathNode::Operator("≆".to_string())),      // unicode-math
        "approxident" => Some(MathNode::Operator("≋".to_string())),  // unicode-math
        "backcong" => Some(MathNode::Operator("≌".to_string())),     // unicode-math
        "arceq" => Some(MathNode::Operator("≘".to_string())),        // unicode-math
        "wedgeq" => Some(MathNode::Operator("≙".to_string())),       // unicode-math
        "veeeq" => Some(MathNode::Operator("≚".to_string())),        // unicode-math
        "stareq" => Some(MathNode::Operator("≛".to_string())),       // unicode-math
        "eqdef" => Some(MathNode::Operator("≝".to_string())),        // unicode-math
        "measeq" => Some(MathNode::Operator("≞".to_string())),       // unicode-math
        "questeq" => Some(MathNode::Operator("≟".to_string())),      // unicode-math
        "Equiv" => Some(MathNode::Operator("≣".to_string())),        // unicode-math
        "nlesssim" => Some(MathNode::Operator("≴".to_string())),     // unicode-math
        "ngtrsim" => Some(MathNode::Operator("≵".to_string())),      // unicode-math
        "nlessgtr" => Some(MathNode::Operator("≸".to_string())),     // unicode-math
        "ngtrless" => Some(MathNode::Operator("≹".to_string())),     // unicode-math
        "cupleftarrow" => Some(MathNode::Operator("⊌".to_string())), // unicode-math
        "cupdot" => Some(MathNode::Operator("⊍".to_string())),       // unicode-math
        "circledequal" => Some(MathNode::Operator("⊜".to_string())), // unicode-math
        "assert" => Some(MathNode::Operator("⊦".to_string())),       // unicode-math
        "prurel" => Some(MathNode::Operator("⊰".to_string())),       // unicode-math
        "scurel" => Some(MathNode::Operator("⊱".to_string())),       // unicode-math
        "hermitmatrix" => Some(MathNode::Identifier("⊹".to_string())), // unicode-math
        "barvee" => Some(MathNode::Operator("⊽".to_string())),       // unicode-math
        "measuredrightangle" => Some(MathNode::Identifier("⊾".to_string())), // unicode-math
        "varlrtriangle" => Some(MathNode::Identifier("⊿".to_string())), // unicode-math
        "smwhtdiamond" => Some(MathNode::Operator("⋄".to_string())), // unicode-math
        "equalparallel" => Some(MathNode::Operator("⋕".to_string())), // unicode-math
        "eqless" => Some(MathNode::Operator("⋜".to_string())),       // unicode-math
        "eqgtr" => Some(MathNode::Operator("⋝".to_string())),        // unicode-math
        "npreccurlyeq" => Some(MathNode::Operator("⋠".to_string())), // unicode-math
        "nsucccurlyeq" => Some(MathNode::Operator("⋡".to_string())), // unicode-math
        "sqsubsetneq" => Some(MathNode::Operator("⋤".to_string())),  // unicode-math
        "sqsupsetneq" => Some(MathNode::Operator("⋥".to_string())),  // unicode-math
        "unicodecdots" => Some(MathNode::Identifier("⋯".to_string())), // unicode-math
        "disin" => Some(MathNode::Operator("⋲".to_string())),        // unicode-math
        "varisins" => Some(MathNode::Operator("⋳".to_string())),     // unicode-math
        "isins" => Some(MathNode::Operator("⋴".to_string())),        // unicode-math
        "isindot" => Some(MathNode::Operator("⋵".to_string())),      // unicode-math
        "varisinobar" => Some(MathNode::Operator("⋶".to_string())),  // unicode-math
        "isinobar" => Some(MathNode::Operator("⋷".to_string())),     // unicode-math
        "isinvb" => Some(MathNode::Operator("⋸".to_string())),       // unicode-math
        "isinE" => Some(MathNode::Operator("⋹".to_string())),        // unicode-math
        "nisd" => Some(MathNode::Operator("⋺".to_string())),         // unicode-math
        "varnis" => Some(MathNode::Operator("⋻".to_string())),       // unicode-math
        "varniobar" => Some(MathNode::Operator("⋽".to_string())),    // unicode-math
        "niobar" => Some(MathNode::Operator("⋾".to_string())),       // unicode-math
        "bagmember" => Some(MathNode::Operator("⋿".to_string())),    // unicode-math
        "house" => Some(MathNode::Identifier("⌂".to_string())),      // unicode-math
        "varbarwedge" => Some(MathNode::Operator("⌅".to_string())),  // unicode-math
        "vardoublebarwedge" => Some(MathNode::Operator("⌆".to_string())), // unicode-math
        "invnot" => Some(MathNode::Identifier("⌐".to_string())),     // unicode-math
        "sqlozenge" => Some(MathNode::Identifier("⌑".to_string())),  // unicode-math
        "profline" => Some(MathNode::Identifier("⌒".to_string())),   // unicode-math
        "profsurf" => Some(MathNode::Identifier("⌓".to_string())),   // unicode-math
        "viewdata" => Some(MathNode::Identifier("⌗".to_string())),   // unicode-math
        "turnednot" => Some(MathNode::Identifier("⌙".to_string())),  // unicode-math
        "inttop" => Some(MathNode::Identifier("⌠".to_string())),     // unicode-math
        "intbottom" => Some(MathNode::Identifier("⌡".to_string())),  // unicode-math
        "varhexagonlrbonds" => Some(MathNode::Identifier("⌬".to_string())), // unicode-math
        "conictaper" => Some(MathNode::Identifier("⌲".to_string())), // unicode-math
        "topbot" => Some(MathNode::Identifier("⌶".to_string())),     // unicode-math
        "obar" => Some(MathNode::Operator("⌽".to_string())),         // unicode-math
        "APLnotslash" => Some(MathNode::Operator("⌿".to_string())),  // unicode-math
        "APLnotbackslash" => Some(MathNode::Identifier("⍀".to_string())), // unicode-math
        "APLboxupcaret" => Some(MathNode::Identifier("⍓".to_string())), // unicode-math
        "APLboxquestion" => Some(MathNode::Identifier("⍰".to_string())), // unicode-math
        "hexagon" => Some(MathNode::Identifier("⎔".to_string())),    // unicode-math
        "lparenuend" => Some(MathNode::Identifier("⎛".to_string())), // unicode-math
        "lparenextender" => Some(MathNode::Identifier("⎜".to_string())), // unicode-math
        "lparenlend" => Some(MathNode::Identifier("⎝".to_string())), // unicode-math
        "rparenuend" => Some(MathNode::Identifier("⎞".to_string())), // unicode-math
        "rparenextender" => Some(MathNode::Identifier("⎟".to_string())), // unicode-math
        "rparenlend" => Some(MathNode::Identifier("⎠".to_string())), // unicode-math
        "lbrackuend" => Some(MathNode::Identifier("⎡".to_string())), // unicode-math
        "lbrackextender" => Some(MathNode::Identifier("⎢".to_string())), // unicode-math
        "lbracklend" => Some(MathNode::Identifier("⎣".to_string())), // unicode-math
        "rbrackuend" => Some(MathNode::Identifier("⎤".to_string())), // unicode-math
        "rbrackextender" => Some(MathNode::Identifier("⎥".to_string())), // unicode-math
        "rbracklend" => Some(MathNode::Identifier("⎦".to_string())), // unicode-math
        "lbraceuend" => Some(MathNode::Identifier("⎧".to_string())), // unicode-math
        "lbracemid" => Some(MathNode::Identifier("⎨".to_string())),  // unicode-math
        "lbracelend" => Some(MathNode::Identifier("⎩".to_string())), // unicode-math
        "vbraceextender" => Some(MathNode::Identifier("⎪".to_string())), // unicode-math
        "rbraceuend" => Some(MathNode::Identifier("⎫".to_string())), // unicode-math
        "rbracemid" => Some(MathNode::Identifier("⎬".to_string())),  // unicode-math
        "rbracelend" => Some(MathNode::Identifier("⎭".to_string())), // unicode-math
        "intextender" => Some(MathNode::Identifier("⎮".to_string())), // unicode-math
        "harrowextender" => Some(MathNode::Identifier("⎯".to_string())), // unicode-math
        "sumtop" => Some(MathNode::Identifier("⎲".to_string())),     // unicode-math
        "sumbottom" => Some(MathNode::Identifier("⎳".to_string())),  // unicode-math
        "overbracket" => Some(MathNode::Identifier("⎴".to_string())), // unicode-math
        "underbracket" => Some(MathNode::Identifier("⎵".to_string())), // unicode-math
        "bbrktbrk" => Some(MathNode::Identifier("⎶".to_string())),   // unicode-math
        "sqrtbottom" => Some(MathNode::Identifier("⎷".to_string())), // unicode-math
        "lvboxline" => Some(MathNode::Identifier("⎸".to_string())),  // unicode-math
        "rvboxline" => Some(MathNode::Identifier("⎹".to_string())),  // unicode-math
        "varcarriagereturn" => Some(MathNode::Identifier("⏎".to_string())), // unicode-math
        "obrbrak" => Some(MathNode::Identifier("⏠".to_string())),    // unicode-math
        "ubrbrak" => Some(MathNode::Identifier("⏡".to_string())),    // unicode-math
        "trapezium" => Some(MathNode::Identifier("⏢".to_string())),  // unicode-math
        "benzenr" => Some(MathNode::Identifier("⏣".to_string())),    // unicode-math
        "strns" => Some(MathNode::Identifier("⏤".to_string())),      // unicode-math
        "fltns" => Some(MathNode::Identifier("⏥".to_string())),      // unicode-math
        "accurrent" => Some(MathNode::Identifier("⏦".to_string())),  // unicode-math
        "elinters" => Some(MathNode::Identifier("⏧".to_string())),   // unicode-math
        "bdtriplevdash" => Some(MathNode::Identifier("┆".to_string())), // unicode-math
        "blockuphalf" => Some(MathNode::Identifier("▀".to_string())), // unicode-math
        "blocklowhalf" => Some(MathNode::Identifier("▄".to_string())), // unicode-math
        "blockfull" => Some(MathNode::Identifier("█".to_string())),  // unicode-math
        "blocklefthalf" => Some(MathNode::Identifier("▌".to_string())), // unicode-math
        "blockrighthalf" => Some(MathNode::Identifier("▐".to_string())), // unicode-math
        "blockqtrshaded" => Some(MathNode::Identifier("░".to_string())), // unicode-math
        "blockhalfshaded" => Some(MathNode::Identifier("▒".to_string())), // unicode-math
        "blockthreeqtrshaded" => Some(MathNode::Identifier("▓".to_string())), // unicode-math
        "mdlgblksquare" => Some(MathNode::Identifier("■".to_string())), // unicode-math
        "mdlgwhtsquare" => Some(MathNode::Identifier("□".to_string())), // unicode-math
        "squoval" => Some(MathNode::Identifier("▢".to_string())),    // unicode-math
        "blackinwhitesquare" => Some(MathNode::Identifier("▣".to_string())), // unicode-math
        "squarehfill" => Some(MathNode::Identifier("▤".to_string())), // unicode-math
        "squarevfill" => Some(MathNode::Identifier("▥".to_string())), // unicode-math
        "squarehvfill" => Some(MathNode::Identifier("▦".to_string())), // unicode-math
        "squarenwsefill" => Some(MathNode::Identifier("▧".to_string())), // unicode-math
        "squareneswfill" => Some(MathNode::Identifier("▨".to_string())), // unicode-math
        "squarecrossfill" => Some(MathNode::Identifier("▩".to_string())), // unicode-math
        "smblksquare" => Some(MathNode::Identifier("▪".to_string())), // unicode-math
        "smwhtsquare" => Some(MathNode::Identifier("▫".to_string())), // unicode-math
        "hrectangleblack" => Some(MathNode::Identifier("▬".to_string())), // unicode-math
        "hrectangle" => Some(MathNode::Identifier("▭".to_string())), // unicode-math
        "vrectangleblack" => Some(MathNode::Identifier("▮".to_string())), // unicode-math
        "vrectangle" => Some(MathNode::Identifier("▯".to_string())), // unicode-math
        "parallelogramblack" => Some(MathNode::Identifier("▰".to_string())), // unicode-math
        "parallelogram" => Some(MathNode::Identifier("▱".to_string())), // unicode-math
        "bigblacktriangleup" => Some(MathNode::Identifier("▲".to_string())), // unicode-math
        "blackpointerright" => Some(MathNode::Identifier("►".to_string())), // unicode-math
        "whitepointerright" => Some(MathNode::Identifier("▻".to_string())), // unicode-math
        "bigblacktriangledown" => Some(MathNode::Identifier("▼".to_string())), // unicode-math
        "blackpointerleft" => Some(MathNode::Identifier("◄".to_string())), // unicode-math
        "whitepointerleft" => Some(MathNode::Identifier("◅".to_string())), // unicode-math
        "mdlgblkdiamond" => Some(MathNode::Identifier("◆".to_string())), // unicode-math
        "mdlgwhtdiamond" => Some(MathNode::Identifier("◇".to_string())), // unicode-math
        "blackinwhitediamond" => Some(MathNode::Identifier("◈".to_string())), // unicode-math
        "fisheye" => Some(MathNode::Identifier("◉".to_string())),    // unicode-math
        "mdlgwhtlozenge" => Some(MathNode::Identifier("◊".to_string())), // unicode-math
        "mdlgwhtcircle" => Some(MathNode::Operator("○".to_string())), // unicode-math
        "dottedcircle" => Some(MathNode::Identifier("◌".to_string())), // unicode-math
        "circlevertfill" => Some(MathNode::Identifier("◍".to_string())), // unicode-math
        "bullseye" => Some(MathNode::Identifier("◎".to_string())),   // unicode-math
        "mdlgblkcircle" => Some(MathNode::Identifier("●".to_string())), // unicode-math
        "circlelefthalfblack" => Some(MathNode::Identifier("◐".to_string())), // unicode-math
        "circlerighthalfblack" => Some(MathNode::Identifier("◑".to_string())), // unicode-math
        "circletophalfblack" => Some(MathNode::Identifier("◓".to_string())), // unicode-math
        "circleurquadblack" => Some(MathNode::Identifier("◔".to_string())), // unicode-math
        "blacklefthalfcircle" => Some(MathNode::Identifier("◖".to_string())), // unicode-math
        "blackrighthalfcircle" => Some(MathNode::Identifier("◗".to_string())), // unicode-math
        "inversebullet" => Some(MathNode::Identifier("◘".to_string())), // unicode-math
        "inversewhitecircle" => Some(MathNode::Identifier("◙".to_string())), // unicode-math
        "ularc" => Some(MathNode::Identifier("◜".to_string())),      // unicode-math
        "urarc" => Some(MathNode::Identifier("◝".to_string())),      // unicode-math
        "lrarc" => Some(MathNode::Identifier("◞".to_string())),      // unicode-math
        "llarc" => Some(MathNode::Identifier("◟".to_string())),      // unicode-math
        "topsemicircle" => Some(MathNode::Identifier("◠".to_string())), // unicode-math
        "botsemicircle" => Some(MathNode::Identifier("◡".to_string())), // unicode-math
        "lrblacktriangle" => Some(MathNode::Identifier("◢".to_string())), // unicode-math
        "llblacktriangle" => Some(MathNode::Identifier("◣".to_string())), // unicode-math
        "ulblacktriangle" => Some(MathNode::Identifier("◤".to_string())), // unicode-math
        "urblacktriangle" => Some(MathNode::Identifier("◥".to_string())), // unicode-math
        "smwhtcircle" => Some(MathNode::Identifier("◦".to_string())), // unicode-math
        "squareleftblack" => Some(MathNode::Identifier("◧".to_string())), // unicode-math
        "squarerightblack" => Some(MathNode::Identifier("◨".to_string())), // unicode-math
        "squareulblack" => Some(MathNode::Identifier("◩".to_string())), // unicode-math
        "squarelrblack" => Some(MathNode::Identifier("◪".to_string())), // unicode-math

        _ => None,
    }
}
